# Generated by Django 5.1.7 on 2025-10-08 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_recipe_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
